### ISSUE TITLE
access_generator.py

### ISSUE THREAD

**Issue by pgreer-splunk** [splunkzilla/Splunk_TA_fit#6]
When starting the access_generator.py script, I end up with it starting on port 8080 as expected, but when going to that URL, I get a 500 internal error:

500 Internal Server Error

The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/lib/python2.7/site-packages/cherrypy/lib/encoding.py", line 217, in __call__
    self.body = self.oldhandler(_args, *_kwargs)
  File "/usr/lib/python2.7/site-packages/cherrypy/_cpdispatch.py", line 61, in __call__
    return self.callable(_self.args, *_self.kwargs)
  File "/home/splunk/etc/apps/Splunk_TA_fit/bin/fitbit.py", line 188, in index
    return query()
UnboundLocalError: local variable 'query' referenced before assignment

Powered by CherryPy 3.5.0

**Comment by splunkzilla** [comment]
Closed externally.
